version: "3"
services:
  db:
    image: docker.io/library/postgres:alpine3.20
    environment:
      POSTGRES_PASSWORD: workout
      POSTGRES_USER: workout
      POSTGRES_DB: workout
    ports:
      - "5432:5432"
